### ISSUE TITLE
Update LWC links/support

### ISSUE THREAD

**Issue by pop4959** [OfficialDonut/SkUniversal#10]
Hey, just noticed you support LWC (which is cool). Unfortunately though, your plugin page is linking to an abandoned version (Modern LWC). I would like to suggest switching this to the maintained version ([LWC Extended](https://www.spigotmc.org/resources/lwc-extended.69551/)).

Thanks!

**Comment by OfficialDonut** [comment]
Updated.

**Comment by pop4959** [comment]
Thanks! 👍
