### ISSUE TITLE
Recipes with air [SlimeFun]

### ISSUE THREAD

**Issue by ShaneBeee** [OfficialDonut/SkUniversal#3]
Hello
Okay, so I was fiddling around with creating new items. I got it all to work after much HARD HARD times with air... apparently it doesn't register AIR as an item, so I had to create an alias at the top of my skript, like air = 0.... so now the recipe in the book works fine and dandy but If I try to craft the recipe it doesn't work. I created a recipe that had 8 furnace, and then the last block was blank.... so put the 8 furnaces in and it didn't recognize it.... IF i make the recipe 9 furnaces, and make it with 9 it works totally fine, its just not registering air what so ever in the enhanced crafting table (which makes sense, because im not putting air in there)... and my guess would be other machines as well maybe

**Comment by ShaneBeee** [comment]
Also,,, I looked at the slime fun API for creating items, it shows item stacks and "null"... I tried null just for the fun of it, also no go. 
Example in the SF API
```SlimefunItem item = new SlimefunItem(category, new CustomItem(new MaterialData(Material.DIAMOND_BLOCK), "&aGreen Diamond Block"), "GREEN_DIAMOND_BLOCK", RecipeType.ENHANCED_CRAFTING_TABLE, new ItemStack[] {null, new ItemStack(Material.DIAMOND), null, null, new ItemStack(Material.DIRT), null, null, new ItemStack(Material.DIAMOND_BLOCK), null});```


I dont know Java at all... but is it possible to do a condition in java, like If i put "air" into my recipe (in the array list I guess), it replaces it with null?

**Comment by OfficialDonut** [comment]
Using air in recipes will now work in v2.3

**Comment by ShaneBeee** [comment]
AWESOME... works like a charm. The only one I can't get working is furnace recipes. But that is probably a fault of SlimeFun... not really sure.

**Comment by OfficialDonut** [comment]
@ShaneBeee I believe it's Slimefun's fault. Unless I missed it Slimefun doesn't have any default items with a furnace recipe so I can't look to see if I'm registering something wrong. 

That being said you can workaround it by registering a furnace recipe yourself. 
```
on skript load:
	set {_recipe::*} to air, air, air, air, dirt, air, air, air, and air
	create slimefun item dirt named "Cool Dirt" with id "COOL_DIRT" in category "RESOURCES" with recipe {_recipe::*} with recipe type "FURNACE"
	register furnace recipe with result slimefun item "COOL_DIRT" using dirt with experience 10
```
That's tuske's furnace recipe syntax, if you dont wanna use tuske i can show you how to do it with skript mirror

**Comment by ShaneBeee** [comment]
Hey I think you are right. I was skimming over SlimeFuns files, and other than their enhanced furnaces. I see nothing at all mentioning furnaces... I have a feeling they added the "recipe type" for it and did nothing.

I have Tuske, so i will give that a try and see what happens. I had issues with Tuske before where the custom named items as ingredients didn't work. 
If you wouldn't mind showing me an example of Skript Mirror I would appreciate it. 
Basically Ill be creating a few things in slime fun, where you will have to smelt custom items in the furnace, therefor it needs to recognize the name of the item in the recipe.
For example I'm creating "Unrefined_Iron" and "Refined_iron" so i'd be smelting iron ingots named "Unrefined Iron" in a furnace, but i don't want a player to smelt regular unnamed iron ingots, and Tuske just wasn't working on my last test. 

Would it be possible to write custom recipe registration (furnace and crafting table) into SkUniversal? 
I only ask because Tuske's seems to be broken when it comes to recipes with custom items, and SkQuery (if that is the other one) doesn't register recipes with custom items.
If not I totally understand, and just tell me to cork it ;)

**Comment by OfficialDonut** [comment]
That's actually not tuske's fault, its a bukkit limitation. From tuske docs:
> About furnace recipe: As said above, the source item will only check the id and data, no planning to add this possibility since the events isn't 'precise' for it. The result item can have name and lore as well, and it can register with a amount of experience that that recipe should give.

so you have to check the item name yourself
```
on fuel burn:
	if slot 0 of event-block is iron ingot:
		if slot 0 of event-block is not slimefun item "UNREFINED_IRON":	
			cancel event

on smelt:
	if slot 0 of event-block is iron ingot:
		if slot 0 of event-block is not slimefun item "UNREFINED_IRON":
			cancel event
```
you could also just stop them from putting the item in the furnace in the first place

**Comment by ShaneBeee** [comment]
UPDATE: I tried with Tuske, and no go on smelting a custom item.... Went over and read the info from tuske regarding recipes in furnace, and this is what it says 
`There is no how to check the source item for the furnace recipe, so it only get the id and data. `
Well.. DAMN you Tuske

**Comment by ShaneBeee** [comment]
HAHA we both replied at the same time. 
Anyways thank you for the info, I will give that a try and see how it goes :)
