### ISSUE TITLE
PlotSquared plot owner and plot id expressions doesn't work

### ISSUE THREAD

**Issue by Vulqa** [OfficialDonut/SkUniversal#6]
Hi,

When i use this code 
```
command /test:
	trigger:
		set {_ID} to the ID of the plot at player
		send "%the ID of the plot at player%"
		send "%owner of plot with ID {_ID}%"
```

It return me always the same thing "0;0" and "Vulqa", even when I’m not on my plot.

**Server's version:** This server is running Paper version git-Paper-569 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**SkUniversal's version:** 2.6
**PlotSquared's version:** 4.189

**Comment by OfficialDonut** [comment]
Hmm that's weird I'll take a look

**Comment by OfficialDonut** [comment]
Fixed https://www.spigotmc.org/resources/skuniversal.45392/update?update=285513
